"""Code harness templates injected into generated scripts."""

METRICS_REPORTER_HARNESS = '''\
# === Scientist-Bin Metrics Harness (auto-injected) ===
import json as _sb_json
import os as _sb_os
import time as _sb_time

_sb_metrics_file = _sb_os.environ.get("SCIENTIST_BIN_METRICS_FILE")
_sb_start_time = _sb_time.monotonic()


def report_metric(name: str, value: float, step: int | None = None) -> None:
    """Report a metric value. Called by generated training code."""
    entry = {
        "name": name,
        "value": value,
        "step": step,
        "elapsed_seconds": round(_sb_time.monotonic() - _sb_start_time, 3),
    }
    if _sb_metrics_file:
        with open(_sb_metrics_file, "a") as f:
            f.write(_sb_json.dumps(entry) + "\\n")
    print(f"METRIC: {name}={value}" + (f" step={step}" if step is not None else ""))

# === End Harness ===

'''

COMPLETION_SENTINEL = "===RESULTS==="


EDA_TEMPLATE = '''\
"""Automated EDA script generated by Scientist-Bin."""

import json
import sys

import pandas as pd

DATA_FILE = {data_file!r}
TARGET_COLUMN = {target_column!r}
PROBLEM_TYPE = {problem_type!r}

try:
    df = pd.read_csv(DATA_FILE)
except Exception as e:
    print(json.dumps({{"error": str(e), "error_type": "data_load_error"}}))
    sys.exit(1)

profile = {{}}
profile["file_path"] = DATA_FILE
profile["shape"] = list(df.shape)
profile["column_names"] = list(df.columns)
profile["dtypes"] = {{col: str(dtype) for col, dtype in df.dtypes.items()}}
profile["missing_counts"] = {{col: int(v) for col, v in df.isnull().sum().items() if v > 0}}

numeric_cols = list(df.select_dtypes(include=["number"]).columns)
categorical_cols = list(df.select_dtypes(include=["object", "category", "bool"]).columns)
profile["numeric_columns"] = numeric_cols
profile["categorical_columns"] = categorical_cols

# Target column analysis
profile["target_column"] = TARGET_COLUMN
if TARGET_COLUMN and TARGET_COLUMN in df.columns:
    if PROBLEM_TYPE == "classification":
        dist = df[TARGET_COLUMN].value_counts().to_dict()
        profile["class_distribution"] = {{
            str(k): int(v) for k, v in dist.items()
        }}
    elif PROBLEM_TYPE == "regression":
        target_stats = df[TARGET_COLUMN].describe()
        profile["target_stats"] = {{str(k): float(v) for k, v in target_stats.items()}}

# Statistics summary
stats_lines = []
desc = df.describe()
stats_lines.append(f"Shape: {{df.shape[0]}} rows x {{df.shape[1]}} columns")
stats_lines.append(f"Numeric columns ({{len(numeric_cols)}}): {{', '.join(numeric_cols[:10])}}")
cat_str = ', '.join(categorical_cols[:10])
stats_lines.append(f"Categorical columns ({{len(categorical_cols)}}): {{cat_str}}")

missing_total = df.isnull().sum().sum()
if missing_total > 0:
    stats_lines.append(f"Total missing values: {{missing_total}}")

duplicates = int(df.duplicated().sum())
if duplicates > 0:
    stats_lines.append(f"Duplicate rows: {{duplicates}}")

if len(numeric_cols) >= 2:
    corr = df[numeric_cols].corr()
    high_corr_pairs = []
    for i in range(len(corr.columns)):
        for j in range(i + 1, len(corr.columns)):
            val = abs(corr.iloc[i, j])
            if val > 0.8:
                high_corr_pairs.append(
                    f"{{corr.columns[i]}} <-> {{corr.columns[j]}}: {{val:.2f}}"
                )
    if high_corr_pairs:
        stats_lines.append(f"High correlations: {{'; '.join(high_corr_pairs[:5])}}")

profile["statistics_summary"] = "\\n".join(stats_lines)

# Data quality issues
issues = []
for col, count in profile["missing_counts"].items():
    pct = count / df.shape[0] * 100
    if pct > 50:
        issues.append(f"Column '{{col}}' has {{pct:.0f}}% missing values")
if duplicates > 0:
    issues.append(f"{{duplicates}} duplicate rows detected")
if TARGET_COLUMN and TARGET_COLUMN in df.columns and PROBLEM_TYPE == "classification":
    class_counts = df[TARGET_COLUMN].value_counts()
    if len(class_counts) > 0:
        imbalance_ratio = class_counts.max() / class_counts.min()
        if imbalance_ratio > 10:
            issues.append(f"Severe class imbalance (ratio {{imbalance_ratio:.1f}}:1)")
profile["data_quality_issues"] = issues

print(json.dumps(profile, default=str))
'''
