"""Code harness templates injected into generated scripts."""

METRICS_REPORTER_HARNESS = '''\
# === Scientist-Bin Metrics Harness (auto-injected) ===
import json as _sb_json
import os as _sb_os
import time as _sb_time

_sb_metrics_file = _sb_os.environ.get("SCIENTIST_BIN_METRICS_FILE")
_sb_start_time = _sb_time.monotonic()


def report_metric(name: str, value: float, step: int | None = None) -> None:
    """Report a metric value. Called by generated training code."""
    entry = {
        "name": name,
        "value": value,
        "step": step,
        "elapsed_seconds": round(_sb_time.monotonic() - _sb_start_time, 3),
    }
    if _sb_metrics_file:
        with open(_sb_metrics_file, "a") as f:
            f.write(_sb_json.dumps(entry) + "\\n")
    print(f"METRIC: {name}={value}" + (f" step={step}" if step is not None else ""))

# Patch pd.read_csv to convert pandas StringDtype to standard object dtype.
# FLAML and some sklearn components cannot handle pandas extension dtypes.
try:
    import pandas as _sb_pd

    _sb_orig_read_csv = _sb_pd.read_csv

    def _sb_read_csv_compat(*args, **kwargs):
        df = _sb_orig_read_csv(*args, **kwargs)
        for col in df.columns:
            if _sb_pd.api.types.is_string_dtype(df[col]) and df[col].dtype != object:
                df[col] = df[col].astype(object)
        return df

    _sb_pd.read_csv = _sb_read_csv_compat
except ImportError:
    pass  # pandas not available in this environment

# === End Harness ===

'''

COMPLETION_SENTINEL = "===RESULTS==="


EDA_TEMPLATE = '''\
"""Automated EDA script generated by Scientist-Bin."""

import json
import sys

import pandas as pd

DATA_FILE = {data_file!r}
TARGET_COLUMN = {target_column!r}
PROBLEM_TYPE = {problem_type!r}

try:
    df = pd.read_csv(DATA_FILE)
except Exception as e:
    print(json.dumps({{"error": str(e), "error_type": "data_load_error"}}))
    sys.exit(1)

profile = {{}}
profile["file_path"] = DATA_FILE
profile["shape"] = list(df.shape)
profile["column_names"] = list(df.columns)
profile["dtypes"] = {{col: str(dtype) for col, dtype in df.dtypes.items()}}
profile["missing_counts"] = {{col: int(v) for col, v in df.isnull().sum().items() if v > 0}}

numeric_cols = list(df.select_dtypes(include=["number"]).columns)
categorical_cols = list(df.select_dtypes(include=["object", "category", "bool"]).columns)
profile["numeric_columns"] = numeric_cols
profile["categorical_columns"] = categorical_cols

# Target column analysis
profile["target_column"] = TARGET_COLUMN
if TARGET_COLUMN and TARGET_COLUMN in df.columns:
    if PROBLEM_TYPE == "classification":
        dist = df[TARGET_COLUMN].value_counts().to_dict()
        profile["class_distribution"] = {{
            str(k): int(v) for k, v in dist.items()
        }}
    elif PROBLEM_TYPE == "regression":
        target_stats = df[TARGET_COLUMN].describe()
        profile["target_stats"] = {{str(k): float(v) for k, v in target_stats.items()}}

# Statistics summary
stats_lines = []
desc = df.describe()
stats_lines.append(f"Shape: {{df.shape[0]}} rows x {{df.shape[1]}} columns")
stats_lines.append(f"Numeric columns ({{len(numeric_cols)}}): {{', '.join(numeric_cols[:10])}}")
cat_str = ', '.join(categorical_cols[:10])
stats_lines.append(f"Categorical columns ({{len(categorical_cols)}}): {{cat_str}}")

missing_total = df.isnull().sum().sum()
if missing_total > 0:
    stats_lines.append(f"Total missing values: {{missing_total}}")

duplicates = int(df.duplicated().sum())
if duplicates > 0:
    stats_lines.append(f"Duplicate rows: {{duplicates}}")

if len(numeric_cols) >= 2:
    corr = df[numeric_cols].corr()
    high_corr_pairs = []
    for i in range(len(corr.columns)):
        for j in range(i + 1, len(corr.columns)):
            val = abs(corr.iloc[i, j])
            if val > 0.8:
                high_corr_pairs.append(
                    f"{{corr.columns[i]}} <-> {{corr.columns[j]}}: {{val:.2f}}"
                )
    if high_corr_pairs:
        stats_lines.append(f"High correlations: {{'; '.join(high_corr_pairs[:5])}}")

profile["statistics_summary"] = "\\n".join(stats_lines)

# Data quality issues
issues = []
for col, count in profile["missing_counts"].items():
    pct = count / df.shape[0] * 100
    if pct > 50:
        issues.append(f"Column '{{col}}' has {{pct:.0f}}% missing values")
if duplicates > 0:
    issues.append(f"{{duplicates}} duplicate rows detected")
if TARGET_COLUMN and TARGET_COLUMN in df.columns and PROBLEM_TYPE == "classification":
    class_counts = df[TARGET_COLUMN].value_counts()
    if len(class_counts) > 0:
        imbalance_ratio = class_counts.max() / class_counts.min()
        if imbalance_ratio > 10:
            issues.append(f"Severe class imbalance (ratio {{imbalance_ratio:.1f}}:1)")
profile["data_quality_issues"] = issues

# Temporal column detection (for time series forecasting)
temporal_columns = []
# Check for datetime dtypes
datetime_cols = list(df.select_dtypes(include=["datetime64", "datetimetz"]).columns)
temporal_columns.extend(datetime_cols)
# Check object columns that look like dates
if not temporal_columns:
    for col in df.select_dtypes(include=["object"]).columns[:5]:
        try:
            parsed = pd.to_datetime(df[col], infer_datetime_format=True, errors="coerce")
            if parsed.notna().sum() > 0.8 * len(df):
                temporal_columns.append(col)
        except Exception:
            pass
# Check for columns with common temporal names
if not temporal_columns:
    for candidate in ["date", "datetime", "timestamp", "time", "ds", "Date", "Timestamp"]:
        if candidate in df.columns:
            temporal_columns.append(candidate)
profile["temporal_columns"] = temporal_columns

# Detect frequency and suggest period for time series
profile["detected_frequency"] = None
profile["suggested_period"] = None
if temporal_columns:
    try:
        tc = temporal_columns[0]
        dt_series = pd.to_datetime(df[tc], errors="coerce").dropna().sort_values()
        if len(dt_series) > 2:
            freq = pd.infer_freq(dt_series)
            profile["detected_frequency"] = freq
            # Suggest period based on frequency
            freq_period_map = {{
                "D": 30, "W": 52, "M": 12, "MS": 12, "H": 24,
                "T": 60, "min": 60, "Q": 4, "QS": 4,
                "Y": 1, "YS": 1, "A": 1, "AS": 1, "B": 22,
            }}
            if freq:
                for key, period in freq_period_map.items():
                    if freq.startswith(key):
                        profile["suggested_period"] = period
                        break
    except Exception:
        pass

# Time series-specific profiling (stationarity, autocorrelation, seasonality)
profile["stationarity"] = None
profile["autocorrelation_values"] = None
profile["seasonal_strength"] = None
profile["trend_direction"] = None
if PROBLEM_TYPE == "ts_forecast" and TARGET_COLUMN and TARGET_COLUMN in df.columns:
    target_series = df[TARGET_COLUMN].dropna()
    if len(target_series) > 10:
        # Stationarity (ADF test)
        try:
            from statsmodels.tsa.stattools import adfuller
            adf_result = adfuller(target_series, autolag="AIC")
            profile["stationarity"] = {{
                "adf_statistic": float(adf_result[0]),
                "p_value": float(adf_result[1]),
                "is_stationary": adf_result[1] < 0.05,
            }}
        except Exception:
            pass

        # Autocorrelation (first 20 lags)
        try:
            from statsmodels.tsa.stattools import acf
            acf_values = acf(target_series, nlags=min(20, len(target_series) // 2 - 1))
            profile["autocorrelation_values"] = [float(v) for v in acf_values.tolist()]
        except Exception:
            pass

        # Seasonal strength (via decomposition)
        try:
            from statsmodels.tsa.seasonal import seasonal_decompose
            period = profile.get("suggested_period") or 12
            if len(target_series) >= 2 * period:
                decomp = seasonal_decompose(target_series.values, model="additive", period=period)
                var_seasonal = float(decomp.seasonal.var())
                var_resid = float(decomp.resid[~pd.isna(decomp.resid)].var())
                total_var = var_seasonal + var_resid
                strength = round(var_seasonal / total_var, 4) if total_var > 0 else 0.0
                profile["seasonal_strength"] = strength
        except Exception:
            pass

        # Trend direction (simple linear slope)
        try:
            x = np.arange(len(target_series))
            slope = float(np.polyfit(x, target_series.values, 1)[0])
            mean_val = float(target_series.mean())
            rel_slope = abs(slope * len(target_series)) / mean_val if mean_val != 0 else 0
            if rel_slope < 0.05:
                profile["trend_direction"] = "stable"
            elif slope > 0:
                profile["trend_direction"] = "increasing"
            else:
                profile["trend_direction"] = "decreasing"
        except Exception:
            pass

print(json.dumps(profile, default=str))
'''
