"""Pydantic models for the summary agent's structured I/O."""

from __future__ import annotations

from pydantic import BaseModel, Field


class ModelRanking(BaseModel):
    """Ranked assessment of a single model from the experiment history."""

    rank: int = Field(..., description="Overall rank (1 = best)")
    algorithm: str = Field(..., description="Algorithm name")
    hyperparameters: dict = Field(
        default_factory=dict, description="Hyperparameters used for this model"
    )
    train_metrics: dict = Field(default_factory=dict, description="Training set metrics")
    val_metrics: dict = Field(
        default_factory=dict, description="Validation / cross-validation metrics"
    )
    test_metrics: dict | None = Field(
        default=None, description="Test set metrics (may be absent for non-final runs)"
    )
    training_time_seconds: float = Field(
        default=0.0, description="Wall-clock training time in seconds"
    )
    strengths: list[str] = Field(default_factory=list, description="Key strengths of this model")
    weaknesses: list[str] = Field(default_factory=list, description="Key weaknesses or limitations")


class ModelRankingList(BaseModel):
    """Wrapper for a list of ModelRanking objects (for structured output)."""

    rankings: list[ModelRanking] = Field(..., description="Models ranked from best to worst")


class BestModelSelection(BaseModel):
    """Structured selection of the best model with reasoning."""

    algorithm: str = Field(..., description="Name of the selected best algorithm")
    hyperparameters: dict = Field(default_factory=dict, description="Best hyperparameters")
    primary_metric_name: str = Field(..., description="Name of the primary evaluation metric")
    primary_metric_value: float = Field(..., description="Value of the primary evaluation metric")
    reasoning: str = Field(..., description="Detailed reasoning for why this model was selected")


class SummaryReport(BaseModel):
    """Comprehensive data-science report generated by the summary agent."""

    title: str = Field(..., description="Report title")
    dataset_overview: str = Field(
        ..., description="Description of the dataset, features, and target variable"
    )
    methodology: str = Field(
        ...,
        description="Methodology section covering plan, preprocessing, and algorithms tried",
    )
    model_comparison_table: str = Field(
        ..., description="Markdown-formatted comparison table of all models"
    )
    best_model_analysis: str = Field(
        ...,
        description=(
            "Deep-dive analysis of the best model: architecture, hyperparameters, performance"
        ),
    )
    hyperparameter_analysis: str = Field(
        ..., description="Analysis of hyperparameter sensitivity and tuning insights"
    )
    conclusions: str = Field(..., description="Key conclusions from the experiment")
    recommendations: list[str] = Field(
        default_factory=list, description="Actionable recommendations for next steps"
    )
    reproducibility_notes: str = Field(..., description="Instructions for reproducing the results")
