"""Pydantic models for the summary agent's structured I/O."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Model ranking (kept from original — used inside ReviewAndRankResult)
# ---------------------------------------------------------------------------


class ModelRanking(BaseModel):
    """Ranked assessment of a single model from the experiment history."""

    rank: int = Field(..., description="Overall rank (1 = best)")
    algorithm: str = Field(..., description="Algorithm name")
    hyperparameters: dict = Field(
        default_factory=dict, description="Hyperparameters used for this model"
    )
    train_metrics: dict = Field(default_factory=dict, description="Training set metrics")
    val_metrics: dict = Field(
        default_factory=dict, description="Validation / cross-validation metrics"
    )
    test_metrics: dict | None = Field(
        default=None, description="Test set metrics (may be absent for non-final runs)"
    )
    training_time_seconds: float = Field(
        default=0.0, description="Wall-clock training time in seconds"
    )
    strengths: list[str] = Field(default_factory=list, description="Key strengths of this model")
    weaknesses: list[str] = Field(default_factory=list, description="Key weaknesses or limitations")


# ---------------------------------------------------------------------------
# Combined review + rank + selection (single LLM call)
# ---------------------------------------------------------------------------


class ReviewAndRankResult(BaseModel):
    """Combined ranking and best-model selection (single LLM call output).

    Replaces the former two-call pattern (ModelRankingList + BestModelSelection).
    """

    rankings: list[ModelRanking] = Field(..., description="Models ranked from best to worst")
    best_algorithm: str = Field(..., description="Name of the selected best algorithm")
    best_hyperparameters: dict = Field(default_factory=dict, description="Best hyperparameters")
    primary_metric_name: str = Field(..., description="Name of the primary evaluation metric")
    primary_metric_value: float = Field(..., description="Value of the primary evaluation metric")
    selection_reasoning: str = Field(
        ..., description="Detailed reasoning for why this model was selected"
    )


# ---------------------------------------------------------------------------
# Enriched summary report
# ---------------------------------------------------------------------------


class SummaryReport(BaseModel):
    """Comprehensive data-science report generated by the summary agent.

    Extended with executive summary, CV stability analysis, feature importance,
    and error analysis sections.
    """

    title: str = Field(..., description="Report title")
    executive_summary: str = Field(
        ..., description="3-5 sentence TL;DR of the experiment and key findings"
    )
    dataset_overview: str = Field(
        ..., description="Description of the dataset, features, and target variable"
    )
    methodology: str = Field(
        ...,
        description="Methodology section covering plan, preprocessing, and algorithms tried",
    )
    model_comparison_table: str = Field(
        ..., description="Markdown-formatted comparison table of all models"
    )
    cv_stability_analysis: str = Field(
        ...,
        description=(
            "Cross-validation stability analysis: per-fold variance, "
            "consistency across folds, and which models are most stable"
        ),
    )
    best_model_analysis: str = Field(
        ...,
        description=(
            "Deep-dive analysis of the best model: architecture, hyperparameters, "
            "performance, overfitting analysis"
        ),
    )
    feature_importance_analysis: str = Field(
        ...,
        description="Analysis of feature importances: top features, their impact, interpretation",
    )
    hyperparameter_analysis: str = Field(
        ..., description="Analysis of hyperparameter sensitivity and tuning insights"
    )
    error_analysis: str = Field(
        ...,
        description=(
            "Confusion matrix interpretation (classification) or residual analysis (regression)"
        ),
    )
    conclusions: str = Field(..., description="Key conclusions from the experiment")
    recommendations: list[str] = Field(
        default_factory=list, description="Actionable recommendations for next steps"
    )
    reproducibility_notes: str = Field(..., description="Instructions for reproducing the results")


# ---------------------------------------------------------------------------
# Diagnostics helper models (used by compute_diagnostics, not LLM output)
# ---------------------------------------------------------------------------


class CVStabilityEntry(BaseModel):
    """Cross-validation stability metrics for one algorithm + metric."""

    algorithm: str
    metric_name: str
    fold_scores: list[float]
    mean: float
    std: float
    cv_coefficient_of_variation: float  # std / mean — lower is more stable
    min_fold: float
    max_fold: float


class OverfitEntry(BaseModel):
    """Train vs validation gap analysis for one algorithm."""

    algorithm: str
    metric_name: str
    train_value: float
    val_value: float
    gap: float  # train - val
    gap_percentage: float  # gap / train * 100
    overfit_risk: str  # "low" | "moderate" | "high"


class HyperparamSensitivityEntry(BaseModel):
    """How much a hyperparameter affects model performance."""

    algorithm: str
    param_name: str
    score_range: float  # max_score - min_score across values tried
    best_value: Any
    values_tried: int
