"""Shared helpers for E2E pipeline tests."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

_BACKEND_DIR = Path(__file__).resolve().parent.parent
_DATA_DIR = _BACKEND_DIR / "data"
_OUTPUTS_DIR = _BACKEND_DIR / "outputs"


def assert_artifact_files(experiment_id: str, check_model: bool = True) -> None:
    """Assert that expected output artifacts were written to disk."""
    results_dir = _OUTPUTS_DIR / "results"
    logs_dir = _OUTPUTS_DIR / "logs"

    result_json = results_dir / f"{experiment_id}.json"
    assert result_json.is_file(), f"Missing results JSON: {result_json}"

    analysis_md = results_dir / f"{experiment_id}_analysis.md"
    assert analysis_md.is_file(), f"Missing analysis report: {analysis_md}"

    summary_md = results_dir / f"{experiment_id}_summary.md"
    assert summary_md.is_file(), f"Missing summary report: {summary_md}"

    plan_json = results_dir / f"{experiment_id}_plan.json"
    assert plan_json.is_file(), f"Missing execution plan: {plan_json}"

    charts_json = results_dir / f"{experiment_id}_charts.json"
    if charts_json.is_file():
        data = json.loads(charts_json.read_text(encoding="utf-8"))
        assert isinstance(data, dict)

    journal = logs_dir / f"{experiment_id}.jsonl"
    assert journal.is_file(), f"Missing decision journal: {journal}"

    if check_model:
        model_path = _OUTPUTS_DIR / "models" / f"{experiment_id}.joblib"
        assert model_path.is_file(), f"Missing model file: {model_path}"


def cleanup_artifacts(experiment_id: str) -> None:
    """Remove artifacts generated by a test run (best effort)."""
    patterns = [
        _OUTPUTS_DIR / "results" / f"{experiment_id}.json",
        _OUTPUTS_DIR / "results" / f"{experiment_id}_analysis.md",
        _OUTPUTS_DIR / "results" / f"{experiment_id}_summary.md",
        _OUTPUTS_DIR / "results" / f"{experiment_id}_plan.json",
        _OUTPUTS_DIR / "results" / f"{experiment_id}_charts.json",
        _OUTPUTS_DIR / "logs" / f"{experiment_id}.jsonl",
        _OUTPUTS_DIR / "models" / f"{experiment_id}.joblib",
    ]
    for path in patterns:
        try:
            path.unlink(missing_ok=True)
        except Exception:
            pass

    run_dir = _OUTPUTS_DIR / "runs" / experiment_id
    if run_dir.is_dir():
        shutil.rmtree(run_dir, ignore_errors=True)

    store_path = _OUTPUTS_DIR / "experiments" / f"{experiment_id}.json"
    try:
        store_path.unlink(missing_ok=True)
    except Exception:
        pass
