"""End-to-end pipeline tests that run the actual ML agent with real datasets.

These tests invoke the real LLM (Google Gemini) and execute real training code.
They are marked ``@pytest.mark.slow`` and skipped when ``GOOGLE_API_KEY`` is
not set, so they run only in local development or dedicated CI stages.

Run with::

    uv run pytest tests/test_e2e_pipeline.py -v --timeout=600 -m slow

"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Path constants
# ---------------------------------------------------------------------------

_BACKEND_DIR = Path(__file__).resolve().parent.parent
_DATA_DIR = _BACKEND_DIR / "data"
_OUTPUTS_DIR = _BACKEND_DIR / "outputs"

IRIS_PATH = _DATA_DIR / "iris_data" / "Iris.csv"
MALL_PATH = _DATA_DIR / "mall_data" / "Mall_Customers.csv"
WINE_PATH = _DATA_DIR / "wine_data" / "WineQT.csv"

_HAS_API_KEY = bool(os.environ.get("GOOGLE_API_KEY"))
_SKIP_REASON = "GOOGLE_API_KEY not set — skipping live E2E test"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _assert_artifact_files(experiment_id: str, check_model: bool = True) -> None:
    """Assert that expected output artifacts were written to disk."""
    results_dir = _OUTPUTS_DIR / "results"
    logs_dir = _OUTPUTS_DIR / "logs"

    result_json = results_dir / f"{experiment_id}.json"
    assert result_json.is_file(), f"Missing results JSON: {result_json}"

    analysis_md = results_dir / f"{experiment_id}_analysis.md"
    assert analysis_md.is_file(), f"Missing analysis report: {analysis_md}"

    summary_md = results_dir / f"{experiment_id}_summary.md"
    assert summary_md.is_file(), f"Missing summary report: {summary_md}"

    plan_json = results_dir / f"{experiment_id}_plan.json"
    assert plan_json.is_file(), f"Missing execution plan: {plan_json}"

    charts_json = results_dir / f"{experiment_id}_charts.json"
    # charts may or may not exist depending on the pipeline; just check if present
    if charts_json.is_file():
        import json

        data = json.loads(charts_json.read_text(encoding="utf-8"))
        assert isinstance(data, dict)

    journal = logs_dir / f"{experiment_id}.jsonl"
    assert journal.is_file(), f"Missing decision journal: {journal}"

    if check_model:
        model_path = _OUTPUTS_DIR / "models" / f"{experiment_id}.joblib"
        assert model_path.is_file(), f"Missing model file: {model_path}"


def _cleanup_artifacts(experiment_id: str) -> None:
    """Remove artifacts generated by a test run (best effort)."""
    patterns = [
        _OUTPUTS_DIR / "results" / f"{experiment_id}.json",
        _OUTPUTS_DIR / "results" / f"{experiment_id}_analysis.md",
        _OUTPUTS_DIR / "results" / f"{experiment_id}_summary.md",
        _OUTPUTS_DIR / "results" / f"{experiment_id}_plan.json",
        _OUTPUTS_DIR / "results" / f"{experiment_id}_charts.json",
        _OUTPUTS_DIR / "logs" / f"{experiment_id}.jsonl",
        _OUTPUTS_DIR / "models" / f"{experiment_id}.joblib",
    ]
    for path in patterns:
        try:
            path.unlink(missing_ok=True)
        except Exception:
            pass

    # Also clean up the per-experiment run directory
    run_dir = _OUTPUTS_DIR / "runs" / experiment_id
    if run_dir.is_dir():
        import shutil

        shutil.rmtree(run_dir, ignore_errors=True)

    # Clean up experiment store JSON
    store_path = _OUTPUTS_DIR / "experiments" / f"{experiment_id}.json"
    try:
        store_path.unlink(missing_ok=True)
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Classification E2E
# ---------------------------------------------------------------------------


@pytest.mark.slow
@pytest.mark.skipif(not _HAS_API_KEY, reason=_SKIP_REASON)
@pytest.mark.skipif(not IRIS_PATH.is_file(), reason=f"Dataset not found: {IRIS_PATH}")
@pytest.mark.timeout(600)
async def test_classification_pipeline_iris():
    """Run the full classification pipeline on the Iris dataset."""
    from scientist_bin_backend.agents.central.agent import CentralAgent
    from scientist_bin_backend.agents.central.schemas import AgentResponse, TrainRequest

    request = TrainRequest(
        objective="Classify iris species from petal and sepal measurements",
        data_file_path=str(IRIS_PATH),
        auto_approve_plan=True,
    )

    agent = CentralAgent()
    result: AgentResponse = await agent.run(request)

    # Basic success checks
    assert result.status != "failed", f"Pipeline failed: {result}"
    assert result.problem_type == "classification"
    assert result.framework == "sklearn"
    assert result.best_model is not None, "No best model selected"
    assert result.iterations >= 1, "Should have at least 1 iteration"

    # Experiment history should have records
    assert len(result.experiment_history) >= 1
    for record in result.experiment_history:
        assert "algorithm" in record
        assert "metrics" in record
        assert "training_time_seconds" in record

    # Plan should exist
    assert result.plan is not None or result.plan_markdown is not None

    # Reports should exist
    assert result.analysis_report is not None
    assert result.summary_report is not None


# ---------------------------------------------------------------------------
# Regression E2E
# ---------------------------------------------------------------------------


@pytest.mark.slow
@pytest.mark.skipif(not _HAS_API_KEY, reason=_SKIP_REASON)
@pytest.mark.skipif(not WINE_PATH.is_file(), reason=f"Dataset not found: {WINE_PATH}")
@pytest.mark.timeout(600)
async def test_regression_pipeline_wine():
    """Run the full regression pipeline on the Wine Quality dataset."""
    from scientist_bin_backend.agents.central.agent import CentralAgent
    from scientist_bin_backend.agents.central.schemas import AgentResponse, TrainRequest

    request = TrainRequest(
        objective="Predict wine quality score from physicochemical properties",
        data_file_path=str(WINE_PATH),
        auto_approve_plan=True,
    )

    agent = CentralAgent()
    result: AgentResponse = await agent.run(request)

    assert result.status != "failed", f"Pipeline failed: {result}"
    assert result.problem_type == "regression"
    assert result.framework == "sklearn"
    assert result.best_model is not None
    assert result.iterations >= 1

    assert len(result.experiment_history) >= 1
    for record in result.experiment_history:
        assert "algorithm" in record
        assert "metrics" in record

    assert result.analysis_report is not None
    assert result.summary_report is not None


# ---------------------------------------------------------------------------
# Clustering E2E
# ---------------------------------------------------------------------------


@pytest.mark.slow
@pytest.mark.skipif(not _HAS_API_KEY, reason=_SKIP_REASON)
@pytest.mark.skipif(not MALL_PATH.is_file(), reason=f"Dataset not found: {MALL_PATH}")
@pytest.mark.timeout(600)
async def test_clustering_pipeline_mall():
    """Run the full clustering pipeline on the Mall Customers dataset."""
    from scientist_bin_backend.agents.central.agent import CentralAgent
    from scientist_bin_backend.agents.central.schemas import AgentResponse, TrainRequest

    request = TrainRequest(
        objective="Segment mall customers into groups based on spending and income",
        data_file_path=str(MALL_PATH),
        auto_approve_plan=True,
    )

    agent = CentralAgent()
    result: AgentResponse = await agent.run(request)

    assert result.status != "failed", f"Pipeline failed: {result}"
    assert result.problem_type == "clustering"
    assert result.framework == "sklearn"
    assert result.best_model is not None
    assert result.iterations >= 1

    assert len(result.experiment_history) >= 1
    for record in result.experiment_history:
        assert "algorithm" in record
        assert "metrics" in record

    assert result.analysis_report is not None
    assert result.summary_report is not None


# ---------------------------------------------------------------------------
# Artifact generation tests
# ---------------------------------------------------------------------------


@pytest.mark.slow
@pytest.mark.skipif(not _HAS_API_KEY, reason=_SKIP_REASON)
@pytest.mark.skipif(not IRIS_PATH.is_file(), reason=f"Dataset not found: {IRIS_PATH}")
@pytest.mark.timeout(600)
async def test_classification_artifacts_saved():
    """Verify that running the pipeline via CLI-like path saves all artifacts."""
    from scientist_bin_backend.agents.central.agent import CentralAgent
    from scientist_bin_backend.agents.central.schemas import AgentResponse, TrainRequest
    from scientist_bin_backend.utils.artifacts import save_experiment_artifacts
    from scientist_bin_backend.utils.naming import generate_experiment_id

    experiment_id = generate_experiment_id("e2e-artifact-test-iris")

    request = TrainRequest(
        objective="Classify iris species for artifact test",
        data_file_path=str(IRIS_PATH),
        auto_approve_plan=True,
    )

    agent = CentralAgent()
    result: AgentResponse = await agent.run(request, experiment_id=experiment_id)

    assert result.status != "failed", f"Pipeline failed: {result}"

    # Save artifacts like the CLI does
    result_dict = result.model_dump()
    save_experiment_artifacts(experiment_id, result_dict)

    try:
        _assert_artifact_files(experiment_id, check_model=True)
    finally:
        _cleanup_artifacts(experiment_id)


@pytest.mark.slow
@pytest.mark.skipif(not _HAS_API_KEY, reason=_SKIP_REASON)
@pytest.mark.skipif(not WINE_PATH.is_file(), reason=f"Dataset not found: {WINE_PATH}")
@pytest.mark.timeout(600)
async def test_regression_artifacts_saved():
    """Verify artifact generation for a regression pipeline run."""
    from scientist_bin_backend.agents.central.agent import CentralAgent
    from scientist_bin_backend.agents.central.schemas import AgentResponse, TrainRequest
    from scientist_bin_backend.utils.artifacts import save_experiment_artifacts
    from scientist_bin_backend.utils.naming import generate_experiment_id

    experiment_id = generate_experiment_id("e2e-artifact-test-wine")

    request = TrainRequest(
        objective="Predict wine quality for artifact test",
        data_file_path=str(WINE_PATH),
        auto_approve_plan=True,
    )

    agent = CentralAgent()
    result: AgentResponse = await agent.run(request, experiment_id=experiment_id)

    assert result.status != "failed", f"Pipeline failed: {result}"

    result_dict = result.model_dump()
    save_experiment_artifacts(experiment_id, result_dict)

    try:
        _assert_artifact_files(experiment_id, check_model=True)
    finally:
        _cleanup_artifacts(experiment_id)


# ---------------------------------------------------------------------------
# API-driven E2E test (via HTTP, verifies store integration)
# ---------------------------------------------------------------------------


@pytest.mark.slow
@pytest.mark.skipif(not _HAS_API_KEY, reason=_SKIP_REASON)
@pytest.mark.skipif(not IRIS_PATH.is_file(), reason=f"Dataset not found: {IRIS_PATH}")
@pytest.mark.timeout(600)
async def test_api_train_endpoint_e2e():
    """Submit a training request via the API and verify the experiment completes.

    Note: This test uses the real _run_training background task, so it requires
    a running event loop. We import the training function directly and await it.
    """
    import tempfile

    from scientist_bin_backend.api.experiments import (
        ExperimentStatus,
        ExperimentStore,
    )
    from scientist_bin_backend.api.routes import _run_training

    with tempfile.TemporaryDirectory() as tmpdir:
        store = ExperimentStore(store_dir=Path(tmpdir))
        experiment = store.create(
            objective="Classify iris via API E2E",
            data_file_path=str(IRIS_PATH),
            framework="sklearn",
        )
        exp_id = experiment.id

        # Patch the global store so _run_training uses our isolated one
        from unittest.mock import patch

        with patch("scientist_bin_backend.api.routes.experiment_store", store):
            await _run_training(
                experiment_id=exp_id,
                objective="Classify iris via API E2E",
                data_description="",
                data_file_path=str(IRIS_PATH),
                framework="sklearn",
                auto_approve_plan=True,
                deep_research=False,
                budget_max_iterations=10,
                budget_time_limit_seconds=600.0,
            )

        updated = store.get(exp_id)
        assert updated is not None
        assert updated.status == ExperimentStatus.completed, (
            f"Expected completed, got {updated.status}. Result: {updated.result}"
        )
        assert updated.result is not None
        assert updated.problem_type == "classification"
        assert updated.framework == "sklearn"
