"""Pydantic models for the campaign orchestrator agent's structured I/O."""

from __future__ import annotations

from pydantic import BaseModel, Field


class Hypothesis(BaseModel):
    """A single hypothesis to be tested via the inner pipeline.

    Generated by the hypothesis-generation node and consumed by the
    experiment runner to formulate a concrete training objective.
    """

    description: str = Field(
        ..., description="One-sentence description of what this hypothesis tests"
    )
    approach: str = Field(
        ...,
        description=(
            "Concrete approach: preprocessing steps, algorithm choice, hyperparameter strategy"
        ),
    )
    algorithm_suggestions: list[str] = Field(
        default_factory=list,
        description="Specific algorithms to try, e.g. ['RandomForestClassifier', 'XGBClassifier']",
    )
    feasibility_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "Estimated feasibility given the data and compute budget (0=infeasible, 1=trivial)"
        ),
    )
    novelty_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="How different this is from already-tested hypotheses (0=duplicate, 1=novel)",
    )
    rationale: str = Field(
        ...,
        description="Why this hypothesis is worth testing, referencing past findings if available",
    )


class HypothesisList(BaseModel):
    """Structured output: a ranked list of hypotheses."""

    hypotheses: list[Hypothesis] = Field(
        ..., description="Hypotheses ranked by expected value (best first)"
    )


class CampaignResult(BaseModel):
    """Final result produced when a campaign finishes."""

    total_iterations: int = Field(..., description="Number of experiments completed")
    total_time_seconds: float = Field(..., description="Wall-clock time for the entire campaign")
    best_experiment_id: str | None = Field(
        default=None, description="ID of the experiment that produced the best result"
    )
    best_algorithm: str | None = Field(
        default=None, description="Algorithm name from the best experiment"
    )
    best_metrics: dict = Field(
        default_factory=dict,
        description="Evaluation metrics from the best experiment",
    )
    hypotheses_tested: int = Field(..., description="Total number of hypotheses that were executed")
    key_findings: list[str] = Field(
        default_factory=list,
        description="Top generalizable findings from the campaign",
    )
