"""Data splitting node: deterministic train/val/test split.

Uses 0 LLM calls -- generates and executes a deterministic splitting script.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from langchain_core.messages import HumanMessage

from scientist_bin_backend.agents.analyst.states import AnalystState
from scientist_bin_backend.events.bus import event_bus
from scientist_bin_backend.events.types import ExperimentEvent
from scientist_bin_backend.execution.runner import CodeRunner, RunConfig

logger = logging.getLogger(__name__)


def _resolve_output_dir(experiment_id: str) -> Path:
    """Resolve the data output directory for an experiment."""
    backend_root = Path(__file__).resolve().parent.parent.parent.parent.parent
    return backend_root / "outputs" / "runs" / experiment_id / "data"


def _build_split_script(
    cleaned_data_path: str,
    output_dir: str,
    target_column: str | None,
    problem_type: str,
) -> str:
    """Build a self-contained Python script for train/val/test splitting."""
    return f'''\
"""Data splitting script generated by Scientist-Bin analyst agent."""

import json
import sys

import pandas as pd
from sklearn.model_selection import train_test_split

CLEANED_DATA_PATH = {cleaned_data_path!r}
OUTPUT_DIR = {output_dir!r}
TARGET_COLUMN = {target_column!r}
PROBLEM_TYPE = {problem_type!r}

try:
    df = pd.read_csv(CLEANED_DATA_PATH)
    total_rows = len(df)

    # Determine stratification
    stratify_col = None
    if PROBLEM_TYPE == "classification" and TARGET_COLUMN and TARGET_COLUMN in df.columns:
        # Only stratify if target has enough samples per class
        value_counts = df[TARGET_COLUMN].value_counts()
        min_class_count = value_counts.min()
        # Need at least 2 samples per class for stratified split
        if min_class_count >= 2:
            stratify_col = df[TARGET_COLUMN]

    # First split: 70% train, 30% temp (val + test)
    train_df, temp_df = train_test_split(
        df,
        test_size=0.30,
        random_state=42,
        stratify=stratify_col,
    )

    # Second split: split temp into 50/50 -> 15% val, 15% test
    stratify_temp = None
    if stratify_col is not None and TARGET_COLUMN in temp_df.columns:
        temp_value_counts = temp_df[TARGET_COLUMN].value_counts()
        if temp_value_counts.min() >= 2:
            stratify_temp = temp_df[TARGET_COLUMN]

    val_df, test_df = train_test_split(
        temp_df,
        test_size=0.50,
        random_state=42,
        stratify=stratify_temp,
    )

    # Save splits
    import os
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    train_path = os.path.join(OUTPUT_DIR, "train.csv")
    val_path = os.path.join(OUTPUT_DIR, "val.csv")
    test_path = os.path.join(OUTPUT_DIR, "test.csv")

    train_df.to_csv(train_path, index=False)
    val_df.to_csv(val_path, index=False)
    test_df.to_csv(test_path, index=False)

    # Compute statistics
    stats = {{
        "train_samples": len(train_df),
        "val_samples": len(val_df),
        "test_samples": len(test_df),
        "train_ratio": round(len(train_df) / total_rows, 4),
        "val_ratio": round(len(val_df) / total_rows, 4),
        "test_ratio": round(len(test_df) / total_rows, 4),
        "stratified": stratify_col is not None,
        "train_path": train_path,
        "val_path": val_path,
        "test_path": test_path,
    }}

    print(json.dumps(stats))

except Exception as e:
    print(json.dumps({{"error": str(e), "error_type": "split_error"}}))
    sys.exit(1)
'''


async def split_data(state: AnalystState) -> dict:
    """Split the cleaned dataset into train/val/test sets.

    This is a deterministic node (0 LLM calls). It generates a splitting
    script based on the problem type and executes it in a subprocess.

    Returns partial state with split_data_paths, split_code, and split_output.
    """
    experiment_id = state.get("experiment_id", "analyst")
    cleaned_data_path = state.get("cleaned_data_path")
    problem_type = state.get("problem_type", "classification")
    data_profile = state.get("data_profile")
    execution_plan = state.get("execution_plan")

    if not cleaned_data_path:
        return {
            "split_code": None,
            "split_output": None,
            "split_data_paths": None,
            "messages": [HumanMessage(content="No cleaned data available, skipping split.")],
        }

    # --- Emit phase start ---
    if experiment_id:
        await event_bus.emit(
            experiment_id,
            ExperimentEvent(
                event_type="phase_change",
                data={"phase": "splitting", "message": "Starting train/val/test split"},
            ),
        )

    # --- Determine target column ---
    target_column = None
    # Try execution_plan first
    if execution_plan:
        target_column = execution_plan.get("target_column")
    # Fall back to data_profile
    if not target_column and data_profile:
        target_column = data_profile.get("target_column")

    # --- Build and execute the split script ---
    output_dir = _resolve_output_dir(experiment_id)
    split_code = _build_split_script(
        cleaned_data_path=cleaned_data_path,
        output_dir=str(output_dir.resolve()),
        target_column=target_column,
        problem_type=problem_type,
    )

    runner = CodeRunner()
    result = await runner.execute(
        RunConfig(
            experiment_id=experiment_id,
            code=split_code,
            run_id="analyst_split",
            timeout_seconds=60,
        )
    )

    if result.success:
        try:
            split_stats = json.loads(result.stdout.strip())

            train_path = split_stats.get("train_path", str(output_dir / "train.csv"))
            val_path = split_stats.get("val_path", str(output_dir / "val.csv"))
            test_path = split_stats.get("test_path", str(output_dir / "test.csv"))

            split_data_paths = {
                "train": train_path,
                "val": val_path,
                "test": test_path,
            }

            stratified = split_stats.get("stratified", False)
            strategy = "stratified" if stratified else "random"
            summary_msg = (
                f"Data split ({strategy}): "
                f"train={split_stats.get('train_samples', '?')} "
                f"({split_stats.get('train_ratio', 0):.1%}), "
                f"val={split_stats.get('val_samples', '?')} "
                f"({split_stats.get('val_ratio', 0):.1%}), "
                f"test={split_stats.get('test_samples', '?')} "
                f"({split_stats.get('test_ratio', 0):.1%})"
            )

            if experiment_id:
                await event_bus.emit(
                    experiment_id,
                    ExperimentEvent(
                        event_type="phase_change",
                        data={"phase": "splitting", "message": summary_msg},
                    ),
                )

            return {
                "split_data_paths": split_data_paths,
                "split_code": split_code,
                "split_output": result.stdout.strip(),
                "messages": [HumanMessage(content=summary_msg)],
            }
        except json.JSONDecodeError:
            logger.warning("Failed to parse split output as JSON: %s", result.stdout[:200])

    # Split failed
    error_msg = result.stderr[:500] if result.stderr else "Unknown split error"
    logger.warning("Data splitting failed: %s", error_msg)

    if experiment_id:
        await event_bus.emit(
            experiment_id,
            ExperimentEvent(
                event_type="error",
                data={"phase": "splitting", "message": f"Split failed: {error_msg}"},
            ),
        )

    return {
        "split_data_paths": None,
        "split_code": split_code,
        "split_output": error_msg,
        "error": f"Split failed: {error_msg}",
        "messages": [HumanMessage(content=f"Data splitting failed: {error_msg}")],
    }
