"""Data splitting node: deterministic train/val/test split.

Uses 0 LLM calls -- generates and executes a deterministic splitting script.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from langchain_core.messages import HumanMessage

from scientist_bin_backend.agents.analyst.states import AnalystState
from scientist_bin_backend.agents.analyst.utils import resolve_run_subdir
from scientist_bin_backend.events.bus import event_bus
from scientist_bin_backend.events.types import ExperimentEvent
from scientist_bin_backend.execution.runner import CodeRunner, RunConfig

logger = logging.getLogger(__name__)


def _resolve_output_dir(experiment_id: str) -> Path:
    return resolve_run_subdir(experiment_id, "data")


def _compute_split_ratios(
    task_analysis: dict | None,
    data_profile: dict | None,
) -> tuple[float, float]:
    """Compute split ratios based on task context.

    Returns (initial_test_size, second_split_ratio) for the two-stage split.
    Default: (0.30, 0.50) gives 70/15/15.
    High complexity: (0.40, 0.50) gives 60/20/20.
    Tiny dataset (<200 rows): (0.20, 0.50) gives 80/10/10.
    Guard: never allocate less than 60% to training.
    """
    # Check dataset size from data_profile first (most concrete signal)
    if data_profile:
        shape = data_profile.get("shape")
        if isinstance(shape, list) and len(shape) >= 1 and shape[0] > 0 and shape[0] < 200:
            return 0.20, 0.50  # 80/10/10 for tiny datasets

    # Check complexity from task_analysis
    if task_analysis:
        complexity = task_analysis.get("complexity_estimate", "medium")
        if complexity == "high":
            return 0.40, 0.50  # 60/20/20 for high complexity

    return 0.30, 0.50  # Default 70/15/15


def _build_split_script(
    cleaned_data_path: str,
    output_dir: str,
    target_column: str | None,
    problem_type: str,
    initial_test_size: float = 0.30,
    second_split_ratio: float = 0.50,
) -> str:
    """Build a self-contained Python script for train/val/test splitting.

    For clustering (unsupervised), produces only a train/test split (no validation set).
    For supervised tasks (classification/regression), produces train/val/test splits.
    """
    if problem_type == "clustering":
        return _build_clustering_split_script(cleaned_data_path, output_dir)
    if problem_type == "ts_forecast":
        return _build_temporal_split_script(
            cleaned_data_path, output_dir, target_column, initial_test_size, second_split_ratio
        )
    return f'''\
"""Data splitting script generated by Scientist-Bin analyst agent."""

import json
import sys

import pandas as pd
from sklearn.model_selection import train_test_split

CLEANED_DATA_PATH = {cleaned_data_path!r}
OUTPUT_DIR = {output_dir!r}
TARGET_COLUMN = {target_column!r}
PROBLEM_TYPE = {problem_type!r}

try:
    df = pd.read_csv(CLEANED_DATA_PATH)
    total_rows = len(df)

    # Determine stratification
    stratify_col = None
    if PROBLEM_TYPE == "classification" and TARGET_COLUMN and TARGET_COLUMN in df.columns:
        # Only stratify if target has enough samples per class
        value_counts = df[TARGET_COLUMN].value_counts()
        min_class_count = value_counts.min()
        # Need at least 2 samples per class for stratified split
        if min_class_count >= 2:
            stratify_col = df[TARGET_COLUMN]

    # First split: train vs temp (val + test)
    train_df, temp_df = train_test_split(
        df,
        test_size={initial_test_size},
        random_state=42,
        stratify=stratify_col,
    )

    # Second split: split temp into val and test
    stratify_temp = None
    if stratify_col is not None and TARGET_COLUMN in temp_df.columns:
        temp_value_counts = temp_df[TARGET_COLUMN].value_counts()
        if temp_value_counts.min() >= 2:
            stratify_temp = temp_df[TARGET_COLUMN]

    val_df, test_df = train_test_split(
        temp_df,
        test_size={second_split_ratio},
        random_state=42,
        stratify=stratify_temp,
    )

    # Save splits
    import os
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    train_path = os.path.join(OUTPUT_DIR, "train.csv")
    val_path = os.path.join(OUTPUT_DIR, "val.csv")
    test_path = os.path.join(OUTPUT_DIR, "test.csv")

    train_df.to_csv(train_path, index=False)
    val_df.to_csv(val_path, index=False)
    test_df.to_csv(test_path, index=False)

    # Compute statistics
    stats = {{
        "train_samples": len(train_df),
        "val_samples": len(val_df),
        "test_samples": len(test_df),
        "train_ratio": round(len(train_df) / total_rows, 4),
        "val_ratio": round(len(val_df) / total_rows, 4),
        "test_ratio": round(len(test_df) / total_rows, 4),
        "stratified": stratify_col is not None,
        "train_path": train_path,
        "val_path": val_path,
        "test_path": test_path,
    }}

    print(json.dumps(stats))

except Exception as e:
    print(json.dumps({{"error": str(e), "error_type": "split_error"}}))
    sys.exit(1)
'''


def _build_temporal_split_script(
    cleaned_data_path: str,
    output_dir: str,
    target_column: str | None,
    initial_test_size: float = 0.30,
    second_split_ratio: float = 0.50,
) -> str:
    """Build a chronological split script for time series data.

    Sorts by temporal column and splits sequentially (no shuffling) to
    prevent data leakage from future to past.
    """
    return f'''\
"""Temporal data splitting script generated by Scientist-Bin analyst agent."""

import json
import os
import sys

import pandas as pd

CLEANED_DATA_PATH = {cleaned_data_path!r}
OUTPUT_DIR = {output_dir!r}
TARGET_COLUMN = {target_column!r}

try:
    df = pd.read_csv(CLEANED_DATA_PATH)
    total_rows = len(df)

    # Detect temporal column: look for datetime dtypes or parseable date columns
    temporal_col = None
    for col in df.columns:
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            temporal_col = col
            break
    if temporal_col is None:
        # Try to parse object columns as dates
        for col in df.select_dtypes(include=["object"]).columns:
            try:
                parsed = pd.to_datetime(df[col], infer_datetime_format=True, errors="coerce")
                if parsed.notna().sum() > 0.8 * len(df):
                    df[col] = parsed
                    temporal_col = col
                    break
            except Exception:
                continue
    if temporal_col is None:
        # Check for columns with common temporal names
        for candidate in ["date", "datetime", "timestamp", "time", "ds", "Date", "Timestamp"]:
            if candidate in df.columns:
                try:
                    df[candidate] = pd.to_datetime(df[candidate], errors="coerce")
                    if df[candidate].notna().sum() > 0.5 * len(df):
                        temporal_col = candidate
                        break
                except Exception:
                    continue

    # Sort chronologically
    if temporal_col is not None:
        df = df.sort_values(temporal_col).reset_index(drop=True)
    # If no temporal column found, assume data is already ordered

    # Chronological split: no shuffling, sequential slicing
    temp_size = {initial_test_size}
    train_end = int(len(df) * (1 - temp_size))
    train_df = df.iloc[:train_end]
    temp_df = df.iloc[train_end:]

    # Split temp into val and test
    val_ratio = 1 - {second_split_ratio}
    val_end = int(len(temp_df) * val_ratio)
    val_df = temp_df.iloc[:val_end]
    test_df = temp_df.iloc[val_end:]

    # Save splits
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    train_path = os.path.join(OUTPUT_DIR, "train.csv")
    val_path = os.path.join(OUTPUT_DIR, "val.csv")
    test_path = os.path.join(OUTPUT_DIR, "test.csv")

    train_df.to_csv(train_path, index=False)
    val_df.to_csv(val_path, index=False)
    test_df.to_csv(test_path, index=False)

    stats = {{
        "train_samples": len(train_df),
        "val_samples": len(val_df),
        "test_samples": len(test_df),
        "train_ratio": round(len(train_df) / total_rows, 4),
        "val_ratio": round(len(val_df) / total_rows, 4),
        "test_ratio": round(len(test_df) / total_rows, 4),
        "stratified": False,
        "temporal_split": True,
        "temporal_column": temporal_col,
        "train_path": train_path,
        "val_path": val_path,
        "test_path": test_path,
    }}

    print(json.dumps(stats))

except Exception as e:
    print(json.dumps({{"error": str(e), "error_type": "split_error"}}))
    sys.exit(1)
'''


def _build_clustering_split_script(
    cleaned_data_path: str,
    output_dir: str,
) -> str:
    """Build a split script for clustering: train (80%) + test (20%) only."""
    return f'''\
"""Clustering data splitting script generated by Scientist-Bin analyst agent."""

import json
import os
import sys

import pandas as pd
from sklearn.model_selection import train_test_split

CLEANED_DATA_PATH = {cleaned_data_path!r}
OUTPUT_DIR = {output_dir!r}

try:
    df = pd.read_csv(CLEANED_DATA_PATH)
    total_rows = len(df)

    # Clustering is unsupervised: simple random train/test split (no validation set)
    train_df, test_df = train_test_split(
        df,
        test_size=0.20,
        random_state=42,
    )

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    train_path = os.path.join(OUTPUT_DIR, "train.csv")
    test_path = os.path.join(OUTPUT_DIR, "test.csv")

    train_df.to_csv(train_path, index=False)
    test_df.to_csv(test_path, index=False)

    stats = {{
        "train_samples": len(train_df),
        "val_samples": 0,
        "test_samples": len(test_df),
        "train_ratio": round(len(train_df) / total_rows, 4),
        "val_ratio": 0.0,
        "test_ratio": round(len(test_df) / total_rows, 4),
        "stratified": False,
        "train_path": train_path,
        "val_path": None,
        "test_path": test_path,
    }}

    print(json.dumps(stats))

except Exception as e:
    print(json.dumps({{"error": str(e), "error_type": "split_error"}}))
    sys.exit(1)
'''


async def split_data(state: AnalystState) -> dict:
    """Split the cleaned dataset into train/val/test sets.

    This is a deterministic node (0 LLM calls). It generates a splitting
    script based on the problem type and executes it in a subprocess.

    Returns partial state with split_data_paths, split_code, and split_output.
    """
    experiment_id = state.get("experiment_id", "analyst")
    cleaned_data_path = state.get("cleaned_data_path")
    problem_type = state.get("problem_type", "classification")
    data_profile = state.get("data_profile")
    execution_plan = state.get("execution_plan")

    if not cleaned_data_path:
        return {
            "split_code": None,
            "split_output": None,
            "split_data_paths": None,
            "messages": [HumanMessage(content="No cleaned data available, skipping split.")],
        }

    # --- Emit phase start ---
    if experiment_id:
        await event_bus.emit(
            experiment_id,
            ExperimentEvent(
                event_type="phase_change",
                data={"phase": "splitting", "message": "Starting train/val/test split"},
            ),
        )

    # --- Determine target column ---
    target_column = None
    # Try execution_plan first
    if execution_plan:
        target_column = execution_plan.get("target_column")
    # Fall back to data_profile
    if not target_column and data_profile:
        target_column = data_profile.get("target_column")

    # --- Compute adaptive split ratios ---
    task_analysis = state.get("task_analysis")
    initial_test_size, second_split_ratio = _compute_split_ratios(task_analysis, data_profile)

    # --- Build and execute the split script ---
    output_dir = _resolve_output_dir(experiment_id)
    split_code = _build_split_script(
        cleaned_data_path=cleaned_data_path,
        output_dir=str(output_dir.resolve()),
        target_column=target_column,
        problem_type=problem_type,
        initial_test_size=initial_test_size,
        second_split_ratio=second_split_ratio,
    )

    runner = CodeRunner()
    result = await runner.execute(
        RunConfig(
            experiment_id=experiment_id,
            code=split_code,
            run_id="analyst_split",
            timeout_seconds=60,
        )
    )

    if result.success:
        try:
            split_stats = json.loads(result.stdout.strip())

            train_path = split_stats.get("train_path", str(output_dir / "train.csv"))
            val_path = split_stats.get("val_path", str(output_dir / "val.csv"))
            test_path = split_stats.get("test_path", str(output_dir / "test.csv"))

            split_data_paths = {
                "train": train_path,
                "val": val_path,
                "test": test_path,
            }

            stratified = split_stats.get("stratified", False)
            strategy = "stratified" if stratified else "random"
            summary_msg = (
                f"Data split ({strategy}): "
                f"train={split_stats.get('train_samples', '?')} "
                f"({split_stats.get('train_ratio', 0):.1%}), "
                f"val={split_stats.get('val_samples', '?')} "
                f"({split_stats.get('val_ratio', 0):.1%}), "
                f"test={split_stats.get('test_samples', '?')} "
                f"({split_stats.get('test_ratio', 0):.1%})"
            )

            if experiment_id:
                await event_bus.emit(
                    experiment_id,
                    ExperimentEvent(
                        event_type="phase_change",
                        data={"phase": "splitting", "message": summary_msg},
                    ),
                )

            return {
                "split_data_paths": split_data_paths,
                "split_code": split_code,
                "split_output": result.stdout.strip(),
                "messages": [HumanMessage(content=summary_msg)],
            }
        except json.JSONDecodeError:
            logger.warning("Failed to parse split output as JSON: %s", result.stdout[:200])

    # Split failed
    error_msg = result.stderr[:500] if result.stderr else "Unknown split error"
    logger.warning("Data splitting failed: %s", error_msg)

    if experiment_id:
        await event_bus.emit(
            experiment_id,
            ExperimentEvent(
                event_type="error",
                data={"phase": "splitting", "message": f"Split failed: {error_msg}"},
            ),
        )

    return {
        "split_data_paths": None,
        "split_code": split_code,
        "split_output": error_msg,
        "error": f"Split failed: {error_msg}",
        "messages": [HumanMessage(content=f"Data splitting failed: {error_msg}")],
    }
