"""Templates for Docker inference container generation."""

from __future__ import annotations

DOCKERFILE_TEMPLATE = """\
FROM python:3.11-slim

LABEL maintainer="scientist-bin"
LABEL description="Model inference server for experiment {experiment_id}"

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model.joblib .
COPY metadata.json .
COPY serve.py .

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"

CMD ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8080"]
"""

REQUIREMENTS_TEMPLATE = """\
scikit-learn=={sklearn_version}
pandas=={pandas_version}
numpy=={numpy_version}
joblib=={joblib_version}
fastapi>=0.115.0
uvicorn>=0.34.0
"""

SERVE_TEMPLATE = '''\
"""Auto-generated inference server for experiment {experiment_id}.

Generated by: scientist-bin deploy
Model: {algorithm}
Problem type: {problem_type}
"""

import json
from pathlib import Path

import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(
    title="Scientist-Bin Inference Server",
    description="Model serving for experiment {experiment_id}",
    version="1.0.0",
)

# Load model and metadata at startup
_MODEL_PATH = Path(__file__).parent / "model.joblib"
_METADATA_PATH = Path(__file__).parent / "metadata.json"

model = joblib.load(_MODEL_PATH)
metadata = json.loads(_METADATA_PATH.read_text(encoding="utf-8"))


class PredictRequest(BaseModel):
    """Request body for predictions."""

    instances: list[dict]


class PredictResponse(BaseModel):
    """Response body for predictions."""

    predictions: list
    probabilities: list | None = None


@app.post("/predict", response_model=PredictResponse)
async def predict(request: PredictRequest) -> PredictResponse:
    """Run inference on the provided instances."""
    try:
        df = pd.DataFrame(request.instances)
    except Exception as exc:
        raise HTTPException(status_code=422, detail=f"Invalid input data: {{exc}}") from exc

    try:
        predictions = model.predict(df).tolist()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Prediction failed: {{exc}}") from exc

    # Return probabilities for classification models
    probabilities = None
    problem_type = metadata.get("problem_type", "classification")
    if problem_type == "classification" and hasattr(model, "predict_proba"):
        try:
            probabilities = model.predict_proba(df).tolist()
        except Exception:
            pass  # Not all classifiers support predict_proba

    return PredictResponse(predictions=predictions, probabilities=probabilities)


@app.get("/health")
async def health() -> dict:
    """Health check endpoint."""
    return {{
        "status": "ok",
        "model": metadata.get("algorithm", "unknown"),
        "experiment_id": metadata.get("experiment_id", "unknown"),
    }}


@app.get("/info")
async def info() -> dict:
    """Model metadata endpoint."""
    return metadata
'''
